author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test6-imagesreadux-deepzoomreadux
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.library.emory.edu/books/emory:r8qzb/pages/emory:r8r44/single-page/
image_size:
  page:
    height: 810
    width: 1000
  small-thumbnail:
    height: 81
    width: 100
  thumbnail:
    height: 243
    width: 300
permalink: pretty
publication_info:
  author: B F White; E J King; J S James.
  date: '2016'
  editors:
  - Atlanta Studies
  tei_xml: tei.xml
  title: 'Original Sacred Harp:
    Digital Scholarly Edition'
show_annotation_author: true
source_info:
  author: B F White; E J King; J S James.
  date: '1911'
  pdf_url: http://readuxout2in.library.emory.edu/books/emory:r8qzb/pdf/
  title: 'Original Sacred Harp'
  url: http://readuxout2in.library.emory.edu/books/emory:r8qzb/
  via_readux: true
tagline: 'Digital Scholarly Edition'
title: 'Original Sacred Harp'
url: https://jpktest.github.io
version: 0.7
